global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "crawler_backend"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["backend:8000"]

